# Generated by Django 4.2.30 on 2026-07-08 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='tryon_results/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('ai_provider', models.CharField(blank=True, max_length=50)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('ai_cost_usd', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('saree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_results', to='products.saree')),
            ],
            options={
                'db_table': 'tryon_results',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TryOnSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_photo', models.ImageField(upload_to='customer_photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('photo_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sarees', models.ManyToManyField(related_name='tryon_sessions', through='tryon.TryOnResult', to='products.saree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryon_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tryon_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tryonresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='tryon.tryonsession'),
        ),
        migrations.AlterUniqueTogether(
            name='tryonresult',
            unique_together={('session', 'saree')},
        ),
    ]
