"""Add customer session models

Revision ID: 3450c91f8b48
Revises: 6dcc9d5e7f48
Create Date: 2026-07-18 23:01:55.152899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3450c91f8b48'
down_revision: Union[str, Sequence[str], None] = '6dcc9d5e7f48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('store_id', sa.String(), nullable=False),
    sa.Column('customer_photo_url', sa.String(), nullable=True),
    sa.Column('session_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_tryons', sa.Integer(), nullable=True),
    sa.Column('selected_sarees_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_sessions_id'), ['id'], unique=False)

    op.create_table('session_selections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('saree_id', sa.String(), nullable=False),
    sa.Column('tryon_result_url', sa.String(), nullable=True),
    sa.Column('is_favorited', sa.Boolean(), nullable=True),
    sa.Column('tried_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['saree_id'], ['sarees.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['customer_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_selections_id'), ['id'], unique=False)

    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('session_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_selections_id'))

    op.drop_table('session_selections')
    with op.batch_alter_table('customer_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_sessions_id'))

    op.drop_table('customer_sessions')
    # ### end Alembic commands ###
