"""store auth restructure

Revision ID: 6dcc9d5e7f48
Revises: 4b69c0eee54b
Create Date: 2026-07-18 22:04:05.452263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dcc9d5e7f48'
down_revision: Union[str, Sequence[str], None] = '4b69c0eee54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('owner_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('owner_phone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('plan_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('daily_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credits_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('credits_per_swap', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('photos_used_today', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_reset_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_index(batch_op.f('ix_stores_store_code'))
        batch_op.create_index(batch_op.f('ix_stores_activation_code'), ['activation_code'], unique=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('ai_credits_remaining')
        batch_op.drop_column('store_code')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_code', sa.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('ai_credits_remaining', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('subscription_plan', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_stores_activation_code'))
        batch_op.create_index(batch_op.f('ix_stores_store_code'), ['store_code'], unique=1)
        batch_op.drop_column('last_reset_date')
        batch_op.drop_column('photos_used_today')
        batch_op.drop_column('credits_per_swap')
        batch_op.drop_column('credits_remaining')
        batch_op.drop_column('daily_limit')
        batch_op.drop_column('plan_type')
        batch_op.drop_column('owner_phone')
        batch_op.drop_column('owner_name')
        batch_op.drop_column('activation_code')

    # ### end Alembic commands ###
