# Generated by Django 4.2.30 on 2026-07-08 19:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Saree',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=100)),
                ('fabric', models.CharField(choices=[('silk', 'Silk'), ('cotton', 'Cotton'), ('chiffon', 'Chiffon'), ('georgette', 'Georgette'), ('organza', 'Organza'), ('linen', 'Linen'), ('banarasi', 'Banarasi'), ('crepe', 'Crepe'), ('net', 'Net'), ('satin', 'Satin'), ('other', 'Other')], default='silk', max_length=50)),
                ('occasion', models.CharField(choices=[('wedding', 'Wedding'), ('festival', 'Festival'), ('party', 'Party'), ('casual', 'Casual'), ('office', 'Office'), ('bridal', 'Bridal')], default='casual', max_length=50)),
                ('barcode_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('barcode_image', models.ImageField(blank=True, null=True, upload_to='barcodes/')),
                ('image_front', models.ImageField(upload_to='sarees/front/')),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='sarees/back/')),
                ('image_closeup', models.ImageField(blank=True, null=True, upload_to='sarees/closeup/')),
                ('image_pallu', models.ImageField(blank=True, null=True, upload_to='sarees/pallu/')),
                ('tryon_image', models.ImageField(upload_to='sarees/tryon/')),
                ('in_stock', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sarees', to='products.category')),
            ],
            options={
                'db_table': 'sarees',
                'ordering': ['-created_at'],
            },
        ),
    ]
